# Generated by Django 5.2.3 on 2025-12-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
    ]
